In [1]:
import pandas as pd
import mysql.connector

conn = mysql.connector.connect(
        ###
        )

cur = conn.cursor()

cur.execute("""
SELECT * FROM scrapy_crawl_results
""")

data = cur.fetchall()

In [3]:
columns = ['date', 'business_name', 'owners', 'owner_name', 'commercial_registered_agent', 'registered_agent']
df = pd.DataFrame(data, columns=columns)
df

,date,business_name,owners,owner_name,commercial_registered_agent,registered_agent
0,2023-01-20,"XH, LLC",NULL,NULL,CORPORATION SERVICE COMPANY,NULL
1,2023-01-20,XERCOR INSURANCE SERVICES LLC,NULL,NULL,COGENCY GLOBAL INC.,NULL
2,2023-01-20,"XENITH, LLC",NULL,NULL,UNITED AGENT GROUP INC.,NULL
3,2023-01-20,Xenex Disinfection Services Inc.,NULL,NULL,"INCORP SERVICES, INC.",NULL
4,2023-01-20,"Xencom Energy Management, LLC",NULL,NULL,"REGISTERED AGENT SOLUTIONS, INC.",NULL
5,2023-01-20,"Xelix Distribution, Inc.",NULL,NULL,C T CORPORATION SYSTEM,NULL
6,2023-01-20,XeCare LLC,NULL,NULL,"CAPITOL CORPORATE SERVICES, INC.",NULL
7,2023-01-20,"XEBU, LLC",NULL,NULL,NULL,"CORPORATE SERVICE CENTER, INC."
8,2023-01-20,XEROX FINANCIAL SERVICES LLC,NULL,NULL,CORPORATION SERVICE COMPANY,NULL
9,2023-01-20,"XZILON, INC.",NULL,NULL,CORPORATION SERVICE COMPANY,NULL
10,2023-01-20,Xcel Automation & Electric LLC,NULL,NULL,NULL,TANNER COLLETTE
11,2023-01-20,XAPIC STUDIOS,NULL,PATRICIA A ROGALLA,NULL,NULL
12,2023-01-20,XCEL AGRONOMY LLC,NULL,NULL,NULL,CHRISTOPHER PERLEBERG
13,2023-01-20,Xander Products & Service LLC,NULL,NULL,NULL,ALEXANDER G. MUGAN
14,2023-01-20,"XCED AVIATION SERVICES, LLC",NULL,NULL,C T CORPORATION SYSTEM,NULL
15,2023-01-20,"XCALIBER INTERNATIONAL LTD., L.L.C.",NULL,NULL,CORPORATION SERVICE COMPANY,NULL
16,2023-01-20,"XANADU PRODUCTS, L.L.C.",NULL,NULL,NULL,RICK PAULSON
17,2023-01-20,XAP Corporation,NULL,NULL,CORPORATION SERVICE COMPANY,NULL
18,2023-01-20,"Xactus, LLC",NULL,NULL,CORPORATION SERVICE COMPANY,NULL
19,2023-01-20,XactlyOne Foundation,NULL,NULL,"NORTHWEST REGISTERED AGENT SERVICE, INC.",NULL
20,2023-01-20,Xcel Holdings LLC,NULL,NULL,NULL,TANNER COLLETTE
21,2023-01-20,Xcel Automation & Electric LLC,NULL,NULL,NULL,TANNER COLLETTE
22,2023-01-20,Xcel Automation,NULL,Xcel Automation & Electric LLC,NULL,NULL
23,2023-01-20,XCEL AGRONOMY LLC,NULL,NULL,NULL,CHRISTOPHER PERLEBERG
24,2023-01-20,Xcel Holdings,NULL,Tanner Collette,NULL,NULL
25,2023-01-20,"XCED AVIATION SERVICES, LLC",NULL,NULL,C T CORPORATION SYSTEM,NULL
26,2023-01-20,XCEL AG SOLUTIONS LLC,NULL,NULL,NULL,ANTHONY BAUMGARTNER
27,2023-01-20,Xcel Aviation,NULL,Tanner S Collette,NULL,NULL
28,2023-01-20,"XCAST LABS, INC.",NULL,NULL,"INCORP SERVICES, INC.",NULL
29,2023-01-20,XCEL ENERGY,NULL,NORTHERN STATES POWER COMPANY,NULL,NULL